// <auto-generated />
using System;
using CyberSecurity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyberSecurity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507152728_UpdateTopics2")]
    partial class UpdateTopics2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyberSecurity.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("ContentBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderIndex = 1,
                            TopicId = 1,
                            Type = "text",
                            Value = "(англ. confidence - доверие) — требование не передавать определенную информацию третьим лицам без согласия её обладателя"
                        },
                        new
                        {
                            Id = 2,
                            OrderIndex = 2,
                            TopicId = 1,
                            Type = "image",
                            Value = "/images/topics/confidence-page.png"
                        },
                        new
                        {
                            Id = 3,
                            OrderIndex = 1,
                            TopicId = 2,
                            Type = "text",
                            Value = "Пароль должен состоять минимум из 12 символов, содержать цифры и спецсимволы."
                        },
                        new
                        {
                            Id = 4,
                            OrderIndex = 2,
                            TopicId = 2,
                            Type = "text",
                            Value = "Давайте попробуем создать безопасный пароль в симуляторе ниже!"
                        },
                        new
                        {
                            Id = 5,
                            OrderIndex = 1,
                            TopicId = 3,
                            Type = "text",
                            Value = "Любые данные в сети разбиваются на пакеты."
                        });
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.GameScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameScores");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.Topics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameRegistryKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Базовые термины ИБ",
                            GameRegistryKey = "crossword",
                            Slug = "confidence",
                            Title = "Конфиденциальность"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Как придумать пароль, который не взломают",
                            GameRegistryKey = "passwordcreator",
                            Slug = "passwords",
                            Title = "Надежные пароли"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Изучаем сетевые пакеты",
                            GameRegistryKey = "downloadtraffic",
                            Slug = "traffic",
                            Title = "Анализ трафика"
                        });
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("CyberSecurity.Domain.Entities.Topics", "Topic")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.GameScore", b =>
                {
                    b.HasOne("CyberSecurity.Domain.Entities.User", "User")
                        .WithMany("GameScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.Topics", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.User", b =>
                {
                    b.Navigation("GameScores");
                });
#pragma warning restore 612, 618
        }
    }
}
