// <auto-generated />
using System;
using CyberSecurity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CyberSecurity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507164056_UpdateTopics4")]
    partial class UpdateTopics4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CyberSecurity.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("ContentBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderIndex = 1,
                            TopicId = 1,
                            Type = "text",
                            Value = "в 2014 году произошла глобальная утечка конфиденциальных данных в Китае - в сеть были выложены более 140 тысяч паспортных данных!"
                        },
                        new
                        {
                            Id = 2,
                            OrderIndex = 2,
                            TopicId = 1,
                            Type = "image",
                            Value = "/images/topics/confidence-page.png"
                        },
                        new
                        {
                            Id = 3,
                            OrderIndex = 1,
                            TopicId = 2,
                            Type = "text",
                            Value = "Тройка самых популярных в мире паролей выглядит так: \"123456\", \"123456789\", \"12345678\", 4, 5 и 6 места занимают \"12345\", \"password\" и \"qwerty\" "
                        },
                        new
                        {
                            Id = 4,
                            OrderIndex = 2,
                            TopicId = 2,
                            Type = "/images/topics/password1.png",
                            Value = ""
                        },
                        new
                        {
                            Id = 5,
                            OrderIndex = 3,
                            TopicId = 2,
                            Type = "/images/topics/password2.png",
                            Value = ""
                        },
                        new
                        {
                            Id = 6,
                            OrderIndex = 4,
                            TopicId = 2,
                            Type = "/images/topics/password3.png",
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            OrderIndex = 1,
                            TopicId = 3,
                            Type = "text",
                            Value = "Ежегодно интернет-трафик растет на 314000%, когда как большинство его генерируется не людьми, а ботами вредоносных программ и поисковыми роботами"
                        },
                        new
                        {
                            Id = 8,
                            OrderIndex = 2,
                            TopicId = 3,
                            Type = "image",
                            Value = "/images/topics/traffic-page1.png"
                        },
                        new
                        {
                            Id = 9,
                            OrderIndex = 3,
                            TopicId = 3,
                            Type = "image",
                            Value = "/images/topics/traffic-page2.png"
                        },
                        new
                        {
                            Id = 10,
                            OrderIndex = 4,
                            TopicId = 3,
                            Type = "image",
                            Value = "/images/topics/traffic-page3.png"
                        },
                        new
                        {
                            Id = 11,
                            OrderIndex = 1,
                            TopicId = 4,
                            Type = "text",
                            Value = "По данным на начало 2026 года, Google обрабатывает более 5,9 триллионов поисковых запросов в год."
                        },
                        new
                        {
                            Id = 12,
                            OrderIndex = 2,
                            TopicId = 4,
                            Type = "image",
                            Value = "/images/topics/internet1.png"
                        },
                        new
                        {
                            Id = 13,
                            OrderIndex = 3,
                            TopicId = 4,
                            Type = "image",
                            Value = "/images/topics/internet2.png"
                        },
                        new
                        {
                            Id = 14,
                            OrderIndex = 4,
                            TopicId = 4,
                            Type = "image",
                            Value = "/images/topics/internet3.png"
                        },
                        new
                        {
                            Id = 15,
                            OrderIndex = 5,
                            TopicId = 4,
                            Type = "image",
                            Value = "/images/topics/internet4.png"
                        },
                        new
                        {
                            Id = 16,
                            OrderIndex = 6,
                            TopicId = 4,
                            Type = "image",
                            Value = "/images/topics/internet5.png"
                        },
                        new
                        {
                            Id = 17,
                            OrderIndex = 1,
                            TopicId = 5,
                            Type = "text",
                            Value = "В настоящее время зарегистрировано 227 млн. сайтов, которые содержат более 65 млрд. веб-страниц"
                        },
                        new
                        {
                            Id = 18,
                            OrderIndex = 2,
                            TopicId = 5,
                            Type = "image",
                            Value = "/images/topics/site-page1.jpg"
                        },
                        new
                        {
                            Id = 19,
                            OrderIndex = 3,
                            TopicId = 5,
                            Type = "image",
                            Value = "/images/topics/site-page2.jpg"
                        });
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.GameScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameScores");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.Topics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameRegistryKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "(англ. confidence - доверие) — требование не передавать определенную информацию третьим лицам без согласия её обладателя",
                            GameRegistryKey = "crossword",
                            Slug = "confidence",
                            Title = "Конфиденциальность"
                        },
                        new
                        {
                            Id = 2,
                            Description = "(фр. parole - слово) - это секретное слово или набор символов, предназначенный для подтверждения личности или полномочий. Пароли используются для защиты информации от несанкционированного доступа.",
                            GameRegistryKey = "passwordcreator",
                            Slug = "password",
                            Title = "Пароль"
                        },
                        new
                        {
                            Id = 3,
                            Description = "(англ. traffic - движение, грузооборот) — объем информации, передаваемой через компьютерную сеть за определенный период времени.",
                            GameRegistryKey = "downloadtraffic",
                            Slug = "traffic",
                            Title = "Трафик"
                        },
                        new
                        {
                            Id = 4,
                            Description = "(aнгл. internet - межсетевой) - средство для получения доступа к библиотекам, играм, аудио и видео-файлам и обмена информацией между людьми, находящимися на разных частях планеты.",
                            GameRegistryKey = "connectiontypes",
                            Slug = "internet",
                            Title = "Интернет"
                        },
                        new
                        {
                            Id = 5,
                            Description = "(от англ. website: web — «паутина, сеть» и site — «место») — система электронных документов, объединенных единой темой, автором или формой под общим адресом (доменным именем)",
                            GameRegistryKey = "buildadomain",
                            Slug = "site",
                            Title = "Сайт"
                        });
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("CyberSecurity.Domain.Entities.Topics", "Topic")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.GameScore", b =>
                {
                    b.HasOne("CyberSecurity.Domain.Entities.User", "User")
                        .WithMany("GameScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.Topics", b =>
                {
                    b.Navigation("ContentBlocks");
                });

            modelBuilder.Entity("CyberSecurity.Domain.Entities.User", b =>
                {
                    b.Navigation("GameScores");
                });
#pragma warning restore 612, 618
        }
    }
}
