CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427094040_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" text NOT NULL,
        "Username" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Role" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427094040_InitialCreate') THEN
    CREATE TABLE "GameScores" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "GameName" text NOT NULL,
        "Score" integer NOT NULL,
        "AchivedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_GameScores" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GameScores_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427094040_InitialCreate') THEN
    CREATE INDEX "IX_GameScores_UserId" ON "GameScores" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427094040_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427094040_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260427094040_InitialCreate', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    CREATE TABLE "Topic" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Slug" text NOT NULL,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "GameRegistryKey" text NOT NULL,
        CONSTRAINT "PK_Topic" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    CREATE TABLE "ContentBlock" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TopicId" integer NOT NULL,
        "OrderIndex" integer NOT NULL,
        "Type" text NOT NULL,
        "Value" text NOT NULL,
        CONSTRAINT "PK_ContentBlock" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContentBlock_Topic_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topic" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    INSERT INTO "Topic" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (1, 'Базовые термины ИБ', 'crossword', 'confidence', 'Конфиденциальность');
    INSERT INTO "Topic" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (2, 'Как придумать пароль, который не взломают', 'passwordcreator', 'passwords', 'Надежные пароли');
    INSERT INTO "Topic" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (3, 'Изучаем сетевые пакеты', 'downloadtraffic', 'traffic', 'Анализ трафика');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    INSERT INTO "ContentBlock" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (1, 1, 1, 'text', '(англ. confidence - доверие) — требование не передавать определенную информацию третьим лицам без согласия её обладателя');
    INSERT INTO "ContentBlock" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (2, 2, 1, 'image', 'images/topics/confidence-page.png');
    INSERT INTO "ContentBlock" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (3, 1, 2, 'text', 'Пароль должен состоять минимум из 12 символов, содержать цифры и спецсимволы.');
    INSERT INTO "ContentBlock" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (4, 2, 2, 'text', 'Давайте попробуем создать безопасный пароль в симуляторе ниже!');
    INSERT INTO "ContentBlock" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (5, 1, 3, 'text', 'Любые данные в сети разбиваются на пакеты.');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    CREATE INDEX "IX_ContentBlock_TopicId" ON "ContentBlock" ("TopicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Topic"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Topic") + 1,
            nextval(pg_get_serial_sequence('"Topic"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"ContentBlock"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ContentBlock") + 1,
            nextval(pg_get_serial_sequence('"ContentBlock"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507135624_InitTopics') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507135624_InitTopics', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    ALTER TABLE "ContentBlock" DROP CONSTRAINT "FK_ContentBlock_Topic_TopicId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    DROP TABLE "Topic";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    ALTER TABLE "ContentBlock" DROP CONSTRAINT "PK_ContentBlock";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    ALTER TABLE "ContentBlock" RENAME TO "ContentBlocks";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    ALTER INDEX "IX_ContentBlock_TopicId" RENAME TO "IX_ContentBlocks_TopicId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    ALTER TABLE "ContentBlocks" ADD CONSTRAINT "PK_ContentBlocks" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    CREATE TABLE "Topics" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Slug" text NOT NULL,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "GameRegistryKey" text NOT NULL,
        CONSTRAINT "PK_Topics" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    INSERT INTO "Topics" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (1, 'Базовые термины ИБ', 'crossword', 'confidence', 'Конфиденциальность');
    INSERT INTO "Topics" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (2, 'Как придумать пароль, который не взломают', 'passwordcreator', 'passwords', 'Надежные пароли');
    INSERT INTO "Topics" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (3, 'Изучаем сетевые пакеты', 'downloadtraffic', 'traffic', 'Анализ трафика');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    ALTER TABLE "ContentBlocks" ADD CONSTRAINT "FK_ContentBlocks_Topics_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topics" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Topics"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Topics") + 1,
            nextval(pg_get_serial_sequence('"Topics"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152137_UpdateTopics') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507152137_UpdateTopics', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152728_UpdateTopics2') THEN
    UPDATE "ContentBlocks" SET "Value" = '/images/topics/confidence-page.png'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507152728_UpdateTopics2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507152728_UpdateTopics2', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "ContentBlocks" SET "Value" = 'в 2014 году произошла глобальная утечка конфиденциальных данных в Китае - в сеть были выложены более 140 тысяч паспортных данных!'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "ContentBlocks" SET "Value" = 'Тройка самых популярных в мире паролей выглядит так: "123456", "123456789", "12345678", 4, 5 и 6 места занимают "12345", "password" и "qwerty" '
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "ContentBlocks" SET "Type" = '/images/topics/password1.png', "Value" = ''
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "ContentBlocks" SET "OrderIndex" = 3, "TopicId" = 2, "Type" = '/images/topics/password2.png', "Value" = ''
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (6, 4, 2, '/images/topics/password3.png', '');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (7, 1, 3, 'text', 'Ежегодно интернет-трафик растет на 314000%, когда как большинство его генерируется не людьми, а ботами вредоносных программ и поисковыми роботами');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (8, 2, 3, 'image', '/images/topics/traffic-page1.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (9, 3, 3, 'image', '/images/topics/traffic-page2.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (10, 4, 3, 'image', '/images/topics/traffic-page3.png');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "Topics" SET "Description" = '(англ. confidence - доверие) — требование не передавать определенную информацию третьим лицам без согласия её обладателя'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "Topics" SET "Description" = '(фр. parole - слово) - это секретное слово или набор символов, предназначенный для подтверждения личности или полномочий. Пароли используются для защиты информации от несанкционированного доступа.', "Slug" = 'password', "Title" = 'Пароль'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    UPDATE "Topics" SET "Description" = '(англ. traffic - движение, грузооборот) — объем информации, передаваемой через компьютерную сеть за определенный период времени.', "Title" = 'Трафик'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    INSERT INTO "Topics" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (4, '(aнгл. internet - межсетевой) - средство для получения доступа к библиотекам, играм, аудио и видео-файлам и обмена информацией между людьми, находящимися на разных частях планеты.', 'connectiontypes', 'internet', 'Интернет');
    INSERT INTO "Topics" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (5, '(от англ. website: web — «паутина, сеть» и site — «место») — система электронных документов, объединенных единой темой, автором или формой под общим адресом (доменным именем)', 'buildadomain', 'site', 'Сайт');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (11, 1, 4, 'text', 'По данным на начало 2026 года, Google обрабатывает более 5,9 триллионов поисковых запросов в год.');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (12, 2, 4, 'image', '/images/topics/internet1.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (13, 3, 4, 'image', '/images/topics/internet2.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (14, 4, 4, 'image', '/images/topics/internet3.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (15, 5, 4, 'image', '/images/topics/internet4.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (16, 6, 4, 'image', '/images/topics/internet5.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (17, 1, 5, 'text', 'В настоящее время зарегистрировано 227 млн. сайтов, которые содержат более 65 млрд. веб-страниц');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (18, 2, 5, 'image', '/images/topics/site-page1.png');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (19, 3, 5, 'image', '/images/topics/site-page2.png');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    PERFORM setval(
        pg_get_serial_sequence('"ContentBlocks"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ContentBlocks") + 1,
            nextval(pg_get_serial_sequence('"ContentBlocks"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Topics"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Topics") + 1,
            nextval(pg_get_serial_sequence('"Topics"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507163818_UpdateTopics3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507163818_UpdateTopics3', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164056_UpdateTopics4') THEN
    UPDATE "ContentBlocks" SET "Value" = '/images/topics/site-page1.jpg'
    WHERE "Id" = 18;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164056_UpdateTopics4') THEN
    UPDATE "ContentBlocks" SET "Value" = '/images/topics/site-page2.jpg'
    WHERE "Id" = 19;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164056_UpdateTopics4') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507164056_UpdateTopics4', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164953_UpdateTopics5') THEN
    UPDATE "ContentBlocks" SET "Type" = 'image', "Value" = '/images/topics/password1.png'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164953_UpdateTopics5') THEN
    UPDATE "ContentBlocks" SET "Type" = 'image', "Value" = '/images/topics/password2.png'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164953_UpdateTopics5') THEN
    UPDATE "ContentBlocks" SET "Type" = 'image', "Value" = '/images/topics/password3.png'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507164953_UpdateTopics5') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507164953_UpdateTopics5', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508181521_UpdateTopics6') THEN
    INSERT INTO "Topics" ("Id", "Description", "GameRegistryKey", "Slug", "Title")
    VALUES (6, 'это метрика, определяющая количество позиций, в которых соответствующие символы двух строк (или векторов) одинаковой длины различаются. ', 'hammingdistance', 'hamming', 'Расстояние Хэмминга');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508181521_UpdateTopics6') THEN
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (20, 1, 6, 'text', 'Расстояние Хэмминга измеряет количество позиций, в которых различаются два битовых набора одинаковой длины. Именно на этом принципе основаны коды Хэмминга, позволяющие технике (жестким дискам, оперативной памяти) находить и исправлять ошибки при передаче или хранении данных.');
    INSERT INTO "ContentBlocks" ("Id", "OrderIndex", "TopicId", "Type", "Value")
    VALUES (21, 2, 6, 'image', '/images/topics/hamming_dist1.png');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508181521_UpdateTopics6') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Topics"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Topics") + 1,
            nextval(pg_get_serial_sequence('"Topics"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"ContentBlocks"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ContentBlocks") + 1,
            nextval(pg_get_serial_sequence('"ContentBlocks"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508181521_UpdateTopics6') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508181521_UpdateTopics6', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508204553_UpdateTopics7') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508204553_UpdateTopics7', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508205412_UpdateTopics8') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508205412_UpdateTopics8', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508205715_UpdateTopics9') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508205715_UpdateTopics9', '10.0.7');
    END IF;
END $EF$;
COMMIT;

